//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafririmWebapi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Option
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Option()
        {
            this.GameSelections = new HashSet<GameSelection>();
        }
    
        public int Id { get; set; }
        public string Desc { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Score { get; set; }
        public string MediaUrl { get; set; }
        public Nullable<int> DilemaId { get; set; }
        public Nullable<int> NextDilemaId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Dilema Dilema { get; set; }
        public virtual Dilema Dilema1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameSelection> GameSelections { get; set; }
    }
}
