//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShafririmWebapi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShafririmEntities : DbContext
    {
        public ShafririmEntities()
            : base("name=ShafririmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Dilema> Dilemas { get; set; }
        public virtual DbSet<Game> Games { get; set; }
        public virtual DbSet<GameSelection> GameSelections { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<Scenario> Scenarios { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
